import { ArrowLeft, Mail, ShieldCheck } from 'lucide-react'
import { Link } from 'react-router-dom'
import { Brand } from '../components/Brand'

function LegalLayout({ title, updated, children }: { title: string; updated: string; children: React.ReactNode }) {
  return <div className="legal-page"><header className="form-header container"><Brand /><Link to="/"><ArrowLeft size={16} /> Voltar ao site</Link></header><main className="legal-container"><div className="legal-heading"><span><ShieldCheck size={19} /> Transparência e segurança</span><h1>{title}</h1><p>Última atualização: {updated}</p></div><article className="legal-content">{children}</article><aside className="legal-contact"><Mail size={22} /><div><strong>Dúvidas ou solicitações sobre seus dados?</strong><p>Entre em contato com o canal de privacidade: <a href="mailto:privacidade@gestok.com.br">privacidade@gestok.com.br</a></p></div></aside></main></div>
}

export function PrivacyPage() {
  return <LegalLayout title="Política de Privacidade" updated="30 de agosto de 2026">
    <p>A Gestok respeita sua privacidade e trata dados pessoais conforme a Lei Geral de Proteção de Dados Pessoais — LGPD (Lei nº 13.709/2018). Esta política explica quais dados coletamos, para que os usamos e quais escolhas você possui.</p>
    <h2>1. Quem controla os dados</h2><p>A operação responsável pela Gestok atua como controladora dos dados coletados neste site e na plataforma. Antes do lançamento comercial, esta seção deverá ser complementada com razão social, CNPJ e endereço da empresa.</p>
    <h2>2. Dados que coletamos</h2><ul><li>Identificação e contato: nome e e-mail;</li><li>Informações profissionais: nome do estabelecimento;</li><li>Perfil da operação: tipo de negócio, canais de venda, número de unidades, quantidade de itens, método de controle e principal desafio;</li><li>Dados da conta e uso: autenticação, produtos, movimentações, configurações, data do último acesso e registros de segurança;</li><li>Imagens enviadas voluntariamente para contagem de estoque e os resultados gerados;</li><li>Dados técnicos essenciais, como endereço IP, navegador, data e hora de acesso, quando necessários à segurança.</li></ul>
    <h2>3. Para que usamos os dados</h2><ul><li>Atender ao diagnóstico solicitado e entrar em contato sobre o teste;</li><li>Criar, autenticar e manter sua conta;</li><li>Entregar as funções de estoque, movimentação, assinatura e contagem por imagem;</li><li>Produzir indicadores agregados de conversão e uso para administrar e melhorar a plataforma;</li><li>Permitir que pessoal administrativo autorizado preste suporte e acompanhe os dados operacionais cadastrados;</li><li>Prevenir fraudes, proteger contas e cumprir obrigações legais, fiscais e regulatórias;</li><li>Enviar marketing apenas quando houver consentimento específico.</li></ul>
    <h2>4. Bases legais</h2><p>Dependendo da atividade, usamos consentimento, execução de contrato ou procedimentos preliminares, cumprimento de obrigação legal e legítimo interesse, sempre com avaliação dos direitos do titular. O consentimento de marketing é opcional e pode ser revogado.</p>
    <h2>5. Compartilhamento e operadores</h2><p>Podemos compartilhar os dados estritamente necessários com fornecedores que sustentam a plataforma, como hospedagem, banco de dados e autenticação (Supabase), pagamentos (Stripe), análise de imagens (OpenAI), comunicação e monitoramento. Esses fornecedores atuam conforme contratos e medidas de segurança próprias. Não vendemos dados pessoais.</p>
    <h2>6. Imagens e inteligência artificial</h2><p>As fotos de estoque são enviadas somente quando você solicita uma contagem. Recomendamos não fotografar pessoas, documentos, telas ou informações pessoais. As imagens são processadas para identificar itens e devem ser removidas após a análise, conforme a configuração técnica da plataforma. O resultado é uma estimativa e precisa ser revisado por uma pessoa.</p>
    <h2>7. Retenção e segurança</h2><p>Mantemos dados pelo período necessário às finalidades descritas, à prestação do serviço e às obrigações legais. Aplicamos controle de acesso por função, criptografia em trânsito, segregação por usuário, registro de último acesso e políticas de banco de dados. O acesso administrativo é restrito a contas expressamente autorizadas. Nenhuma medida elimina todos os riscos, por isso revisamos os controles periodicamente.</p>
    <h2>8. Seus direitos</h2><p>Você pode solicitar confirmação e acesso, correção, anonimização, bloqueio ou eliminação, portabilidade quando aplicável, informações sobre compartilhamento, revisão de decisões automatizadas, revogação de consentimento e oposição nos casos previstos em lei. Poderemos confirmar sua identidade antes de atender à solicitação.</p>
    <h2>9. Comunicações e consentimento</h2><p>Mensagens relacionadas à conta e ao serviço podem ser necessárias para executar o contrato. Mensagens promocionais dependem da sua escolha. Você pode usar o link de descadastro ou contatar nosso canal de privacidade a qualquer momento.</p>
    <h2>10. Alterações desta política</h2><p>Podemos atualizar este documento para refletir mudanças no produto ou na legislação. Alterações relevantes serão comunicadas pelos canais disponíveis.</p>
  </LegalLayout>
}

export function TermsPage() {
  return <LegalLayout title="Termos de Uso" updated="30 de agosto de 2026">
    <p>Estes termos regulam o acesso à Gestok. Ao criar uma conta, você declara ter capacidade para representar o estabelecimento informado e concorda com as condições abaixo.</p>
    <h2>1. Serviço</h2><p>A Gestok oferece recursos para cadastro de produtos, acompanhamento de saldos, registro de movimentações e apoio à contagem por imagem. A ferramenta auxilia a gestão, mas não substitui conferência física, controles sanitários, fiscais, contábeis ou decisões profissionais.</p>
    <h2>2. Conta e segurança</h2><p>Você deve fornecer dados corretos, proteger suas credenciais e avisar sobre uso não autorizado. As ações realizadas na conta são de responsabilidade do titular, salvo falha comprovadamente atribuível à plataforma.</p>
    <h2>3. Teste gratuito e assinatura</h2><p>Contas elegíveis recebem 7 dias de teste. Não é necessário cartão para iniciar. Para continuar após esse período, é preciso ativar uma assinatura no Stripe. Quando o cartão é cadastrado durante o teste, a primeira cobrança é programada para o fim do período indicado no checkout. Preço, periodicidade, tributos e data da cobrança serão exibidos antes da confirmação.</p>
    <h2>4. Cancelamento</h2><p>A renovação pode ser cancelada pelo portal de cobrança. O acesso pago permanece até o fim do período já contratado, salvo regra diferente claramente apresentada no checkout ou exigência legal.</p>
    <h2>5. Uso adequado</h2><p>Não é permitido tentar acessar dados de terceiros, contornar controles de segurança, enviar conteúdo ilícito, usar a plataforma para fraude ou sobrecarregar intencionalmente a infraestrutura.</p>
    <h2>6. Contagem por IA</h2><p>Resultados de inteligência artificial são estimativas e podem conter erros. O usuário deve revisar e confirmar cada item antes de utilizá-lo na operação. A Gestok não garante precisão integral em imagens desfocadas, obstruídas ou com produtos visualmente semelhantes.</p>
    <h2>7. Disponibilidade e evolução</h2><p>Recursos beta podem mudar, ser suspensos ou apresentar instabilidade. Buscaremos manter o serviço disponível e comunicar manutenções relevantes, mas não garantimos funcionamento ininterrupto.</p>
    <h2>8. Responsabilidades</h2><p>Cada usuário responde pela qualidade dos dados inseridos e pelas decisões tomadas a partir deles. Eventuais limites de responsabilidade devem respeitar os direitos irrenunciáveis previstos na legislação brasileira.</p>
    <h2>9. Propriedade intelectual</h2><p>A marca, interface e código da Gestok pertencem aos seus titulares. O usuário mantém a titularidade dos dados da sua operação e concede apenas as permissões necessárias para prestar o serviço.</p>
    <h2>10. Lei aplicável</h2><p>Aplicam-se as leis da República Federativa do Brasil. Antes do lançamento comercial, este documento deve receber revisão jurídica e identificação completa da empresa responsável.</p>
  </LegalLayout>
}
